#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include "../include/gui/main_form.hpp"
#include <xtd/startup.h>

startup_(Virtware::main_form);
#pragma endregion
