#pragma region xtd generated code
// This code was generated by CMake script.
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.

#include <xtd/tunit/tunit_main.h>
#include <xtd/startup.h>

startup_(tunit_main_);
#pragma endregion
